plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.yourname.chess'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.jar {
    archiveBaseName = "chess-engine-core"

    include("engine/**")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = 'com.juricektadeas.chess'
            artifactId = 'chess-engine-core'
            version = '0.5.0'
        }
    }
    repositories {
        mavenLocal()
    }
}
